project:
  type: website
  output-dir: docs
  preview:
    browser: true

website:
  title: " {{< fa image-portrait >}} Sara(Yuhua) Zong"
  navbar:
    left:
      - href: index.qmd
        text: "{{< fa regular hand-spock >}} Hello"
      - text: "{{< fa regular lightbulb >}} Learn How"
        menu: 
          # - href: pkg_unit_test_1.qmd
          #   text: "Unit Test"
          - href: setup_homebrew_2.qmd
            text: "Homebrew"
          # - href: transformation_python_3.qmd
          #   text: "Clean Data Python"
          # - href: shiny_basics_5.qmd
          #   text: "Shiny Basics"
          # - href: shiny_3dscatter_plotly_6.qmd
          #   text: "Shiny 3D Scatter"
          

format:
  html:
    # theme: cosmo
    theme: sandstone
    css: styles.css
    toc: true


