project:
  type: website
  output-dir: docs
  preview:
    browser: true

website:
  title: " {{< fa image-portrait >}} Sara(Yuhua) Zong"
  navbar:
    left:
      - href: index.qmd
        text: "{{< fa regular hand-spock >}} Hello"
      - text: "{{< fa regular lightbulb >}} Learn How"
        menu: 
          - href: l1_unit_test.qmd
            text: "Unit Test"
          - href: l2_homebrew.qmd
            text: "Homebrew"
          # - href: l3_transformation_python.qmd
          #   text: "Clean Data Python"
          # - href: l4_transformation_polars.qmd
          #   text: "Clean Data Polar"
          # - href: l5_shiny_basics.qmd
          #   text: "Shiny Basics"
          # - href: l6_shiny_golem.qmd
          #   text: "Shiny Golem"
          # - href: l7_shiny_3dscatter.qmd
          #   text: "Shiny 3D Scatter"
          

format:
  html:
    # theme: cosmo
    theme: sandstone
    css: styles.css
    toc: true


